### ISSUE TITLE
Add tutorial(s): How to create factsheets

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/academy#147]
Some users of the OEP may wonder  how (and why) to create factsheets. Currently there is no straight forward description pointing out the functionality and how to use it (and why). 

I am not sure whether now is a good time, since some of the factsheets are still not in a stable state (e.g. scenario, study), but in general I think it would be good to have  tutorials that describe :

- How and why to create a scenario factsheet
- How and why  to create a study factsheet
- How and why  to create a models factsheet
- How and why to create a framework factsheet

Such tutorials should include easy to use instructions for first time contributors and - where necessary - also contain some contextual information.

I'll initially assign myself and some others. 
cc @l-emele @wingechr

**Comment by han-f** [comment]
now  getting cc @adelmemariani  aboard too so we can exchange when best time to approach this could be.

**Comment by adelmemariani** [comment]
@han-f  It is now possible for the users to add study factsheets. Please see this PR: https://github.com/OpenEnergyPlatform/oeplatform/pull/932
The data on the server should be replaced in order to see the effect (current data is not very clean)
Still, adding model_calculation is missing, however, it is a big step forward :)

**Comment by han-f** [comment]
@adelmemariani - this sounds great, thanks for letting me know. I am happy to test anytime it is live somewhere - either toep or directly on OEP. 
How will it work to replace the data on the server?

**Comment by adelmemariani** [comment]
@han-f  - I was thinking we could easily replace the current data with my local data, but I realized that the current data (live server) is somehow important and cannot be easily replaced because I think I have some information about the ontology in my local knowledge graph and the data on the live server differs or does not contain the ontology information. This is why we cannot see elements in the dropdown menus for energy carriers in the current release. I am working on this issue, and I will update here as soon as I have new information.

**Comment by han-f** [comment]
I close this issue, as we now have the scenario bundles, and once they are stable, we can create a course for these instead.
